version: "3"
services:
  # api_service:
  #   container_name: api-finances-v2
  #   build:
  #     context: ../api-financesv2
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3333:3333"
  #   volumes:
  #     - .:/myapp
  #   command: ["rails", "server", "-b", "0.0.0.0", "-p", "3333"]
  #   networks:
  #     - shared_network

  app_finances:
    container_name: app-finances
    # depends_on:
    #   - api_service
    build:
      context: ./app-finances-root
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - shared_network

  app_transactions:
    container_name: app-transactions
    depends_on:
      - app_finances
    build:
      context: ./app-transactions
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - shared_network

  app_accounts:
    container_name: app-accounts
    depends_on:
      - app_finances
    build:
      context: ./app-my-account
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    # networks:
    #   - shared_network
networks:
  shared_network:
    driver: bridge
## docker-compose up --build -d
