version: "3"
services:
  app_transactions:
    container_name: app-transactions
    # depends_on:
    #   - app_finances
    build:
      context: ./app-transactions
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - shared_network

  app_accounts:
    container_name: app-accounts
    # depends_on:
    #   - app_finances
    build:
      context: ./app-my-account
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    # networks:
    #   - shared_network

  app_finances:
    container_name: app-finances
    depends_on:
      - app_transactions
      - app_accounts
    build:
      context: ./app-finances-root
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
## docker-compose up --build -d
